version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - playpauseandstop
  assignees:
  - playpauseandstop
